server:
  port: 9402


###服务注册到eureka地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8100/eureka
#      ##defaultZone: http://localhost:8100/eureka,http://localhost:8101/eureka,http://localhost:8102/eureka
#    ###因为该应用为注册中心，不会注册自己
#    register-with-eureka: true
#    ###是否需要从eureka上获取注册信息
#    fetch-registry: true
#  instance:
#    #注册时使用ip而不是主机名
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 2
#    lease-expiration-duration-in-seconds: 4
spring:
  application:
    name: zuul-helloworld

param:
  ip: 10.1.234.123
  port: 8240
  addr: ${param.ip}:${param.port}